theme: hexo-theme-Claudia  # 指定主题

language: zh-CN  # 指定语言，会影响主题显示的语言，按需修改

url: https://swordrada.github.io
root: /

comment_utteranc:
  enable: true
  repo: swordrada/swordrada.github.io

deploy:
  type: git
  repo: git@github.com:swordrada/swordrada.github.io.git
  branch: master